# Syncthing - peer-to-peer file sync.
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: apps
  source:
    repoURL: https://github.com/ned-si/homelab.git
    targetRevision: main
    path: apps/syncthing
  destination:
    server: https://kubernetes.default.svc
    namespace: syncthing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
