apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - "ReadWriteOnce"
                  resources:
                    requests:
                      storage: 15Gi
        grafana:
          defaultDashboardsTimezone: browser
          grafana.ini:
            server:
              domain: grafana.lilalala.com
              root_url: https://%(domain)s/
          ingress:
            ingressClassName: nginx
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              external-dns.alpha.kubernetes.io/target: 178.39.124.203
            hosts:
            - grafana.lilalala.com
            tls: 
            - secretName: grafana-general-tls
              hosts:
                - grafana.lilalala.com
        releaseName: kube-prometheus-stack
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: v56.2.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true


  ingress:
    ## If true, Grafana Ingress will be created
    ##
    enabled: false

    ## IngressClassName for Grafana Ingress.
    ## Should be provided if Ingress is enable.
    ##
    # ingressClassName: nginx

    ## Annotations for Grafana Ingress
    ##
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"

    ## Labels to be added to the Ingress
    ##
    labels: {}

    ## Hostnames.
    ## Must be provided if Ingress is enable.
    ##
    # hosts:
    #   - grafana.domain.com
    hosts: []

    ## Path for grafana ingress
    path: /

    ## TLS configuration for grafana Ingress
    ## Secret must be manually created in the namespace
    ##
    tls: []
    # - secretName: grafana-general-tls
    #   hosts:
    #   - grafana.example.com

