apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    helm:
      values: |
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - "ReadWriteOnce"
                  resources:
                    requests:
                      storage: 15Gi
        grafana:
          defaultDashboardsTimezone: browser
          assertNoLeakedSecrets: false
          grafana.ini:
            server:
              domain: grafana.lilalala.com
              root_url: https://%(domain)s/
            auth.generic_oauth:
              enabled: true
              name: Keycloak-OAuth
              allow_sign_up: true
              client_id: grafana-oauth
              client_secret: REDACTED
              scopes: openid email profile offline_access roles
              email_attribute_path: email
              login_attribute_path: username
              name_attribute_path: full_name
              auth_url: https://auth.lilalala.com/realms/homelab/protocol/openid-connect/auth
              token_url: https://auth.lilalala.com/realms/homelab/protocol/openid-connect/token
              api_url: https://auth.lilalala.com/realms/homelab/protocol/openid-connect/userinfo
              role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'editor') && 'Editor' || 'Viewer'
          ingress:
            ingressClassName: nginx
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              external-dns.alpha.kubernetes.io/target: 178.39.124.203
            hosts:
            - grafana.lilalala.com
            pathType: ImplementationSpecific
            tls: 
            - secretName: grafana-general-tls
              hosts:
                - grafana.lilalala.com
        releaseName: kube-prometheus-stack
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: v56.2.0
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
