---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: qbittorrent
  name: qbittorrent
  namespace: theater
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: qbittorrent
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: qbittorrent
  name: qbittorrent-seed
  namespace: theater
spec:
  type: LoadBalancer
  ports:
    - name: seed
      port: 50000
      targetPort: seed
      protocol: TCP
  selector:
    app.kubernetes.io/name: qbittorrent
