---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: seafile
  name: seafile
  namespace: seafile
spec:
  replicas: 1
  strategy:
    # rollingUpdate: null #this errors with argo for some reason
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: seafile
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seafile
    spec:
      containers:
        - name: seafile
          image: seafileltd/seafile-mc:11.0-latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: "mariadb"
            - name: DB_ROOT_PASSWD
              value: "REDACTED" #db's password
            - name: TIME_ZONE
              value: "Europe/Zurich"
            - name: SEAFILE_ADMIN_EMAIL
              value: "nedsi@pm.me" #admin email
            - name: SEAFILE_ADMIN_PASSWORD
              value: "REDACTED" #admin password
            - name: SEAFILE_SERVER_LETSENCRYPT
              value: "false"
            - name: SEAFILE_SERVER_HOSTNAME
              value: "https://drive.lilalala.com" #hostname
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              memory: "1000Mi"
          volumeMounts:
            - name: seafile-data
              mountPath: /shared
      volumes:
        - name: seafile-data
          persistentVolumeClaim:
            claimName: seafile-pvc
