apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: igontfh79hks@opayq.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector: {}
        dns01:
          webhook:
            groupName: acme.lilalala.com
            solverName: dynadot
            config:
              DYNADOTAPI_Token="REDACTED"
              DYNADOT_ADD_DNS_SLEEP=1800
              DYNADOT_REMOVE_DNS_SLEEP=1800
              DYNADOTAPI_API_RETRIES=5
              DYNADOTAPI_RETRY_SLEEP=30
