---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: lidarr
  name: lidarr
  namespace: theater
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8686
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: lidarr
