---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: lidarr
  name: lidarr
  namespace: theater
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lidarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lidarr
    spec:
      containers:
        - name: lidarr
          image: ghcr.io/hotio/lidarr:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/Zurich
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: UMASK
              value: "002"
            # - name: LIDARR__LOG__DBENABLED
            #   value: "false"
            - name: LIDARR__POSTGRES__HOST
              valueFrom:
                secretKeyRef:
                  name: lidarr-postgresql-app
                  key: host
            - name: LIDARR__POSTGRES__PORT
              valueFrom:
                secretKeyRef:
                  name: lidarr-postgresql-app
                  key: port
            - name: LIDARR__POSTGRES__USER
              valueFrom:
                secretKeyRef:
                  name: lidarr-postgresql-app
                  key: user
            - name: LIDARR__POSTGRES__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lidarr-postgresql-app
                  key: password
            - name: LIDARR__POSTGRES__MAINDB
              valueFrom:
                secretKeyRef:
                  name: lidarr-postgresql-app
                  key: dbname
            - name: LIDARR__SERVER__URLBASE
              value: /arr/lidarr
          ports:
            - name: http
              containerPort: 8686
              protocol: TCP
          volumeMounts:
            - name: media
              mountPath: /data
      volumes:
        - name: media
          nfs:
            server: 192.168.1.228
            path: /mnt/homelab/k8s/nfs
