#!/bin/bash
# gen-crd-schemas.sh -- regenerate the vendored kubeconform CRD schemas in ci/schemas/.
#
# kubeconform validates CRD kinds against these files (no network catalogue, no
# -ignore-missing-schemas): a kind without a schema fails CI. Adding a CRD kind
# means adding its pinned source here and committing the regenerated output in
# the same PR. Every source is a tag or release asset; the sha256 of each fetched
# file is written to ci/schemas/SOURCES.txt (sha256sum format) so a regeneration
# is reviewable.
#
# Converter: kubeconform's scripts/openapi2jsonschema.py at the v0.7.0 tag,
# fetched by commit SHA and checked against its sha256. It needs PyYAML:
# PYTHON=<interpreter with PyYAML> (the CI venv from ci/requirements-ci.txt has it).
#
# Output names: <group>_<kind>_<version>.json (lowercase), matched by
#   -schema-location 'ci/schemas/{{.Group}}_{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'
# When two sources define the same group/kind/version (Cilium 1.16.3 and 1.17.x),
# the later source wins: 1.17.x is written last, as the superset used during the
# Cilium transition.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="$ROOT/ci/schemas"
PYTHON=${PYTHON:-python3}

O2J_URL="https://raw.githubusercontent.com/yannh/kubeconform/e65429b1e5990dd019ebb7b5642dcd22a3e9cd13/scripts/openapi2jsonschema.py"
O2J_SHA256="d145babfbb765004030764e1b4e518bfb7a4bd7f111691a08fa57983b81881f3"

ARGOCD=v2.14.11
CERT_MANAGER=v1.15.0
CNPG=1.24.1
CILIUM_OLD=v1.16.3
CILIUM_NEW=v1.17.18
GATEWAY_API=v1.2.0
PROM_OPERATOR=v0.94.1
SNAPSHOTTER=v6.3.2
BARMAN=v0.12.0
# CustomResourceDefinition itself: yannh/kubernetes-json-schema has no schema for
# it (JSONSchemaProps is recursive), so it is built from the Kubernetes OpenAPI v3
# document of the validated version with JSONSchemaProps left opaque.
K8S_OPENAPI="https://raw.githubusercontent.com/kubernetes/kubernetes/v1.31.2/api/openapi-spec/v3/apis__apiextensions.k8s.io__v1_openapi.json"
CRD_DEF="io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinition"
CRD_OPAQUE="io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps"

"$PYTHON" -c 'import yaml' 2>/dev/null || {
  echo "gen-crd-schemas: $PYTHON lacks PyYAML; set PYTHON to the CI venv interpreter" >&2
  exit 1
}

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

sha256() { if command -v sha256sum >/dev/null; then sha256sum "$1" | cut -d' ' -f1; else shasum -a 256 "$1" | cut -d' ' -f1; fi; }

curl -fsSL -m 60 -o "$work/openapi2jsonschema.py" "$O2J_URL"
[ "$(sha256 "$work/openapi2jsonschema.py")" = "$O2J_SHA256" ] || { echo "openapi2jsonschema.py sha256 mismatch" >&2; exit 1; }

sources=()
add() { sources+=("$1"); }

add "https://raw.githubusercontent.com/argoproj/argo-cd/$ARGOCD/manifests/crds/application-crd.yaml"
add "https://raw.githubusercontent.com/argoproj/argo-cd/$ARGOCD/manifests/crds/applicationset-crd.yaml"
add "https://raw.githubusercontent.com/argoproj/argo-cd/$ARGOCD/manifests/crds/appproject-crd.yaml"
add "https://github.com/cert-manager/cert-manager/releases/download/$CERT_MANAGER/cert-manager.crds.yaml"
add "https://raw.githubusercontent.com/cloudnative-pg/cloudnative-pg/v$CNPG/releases/cnpg-$CNPG.yaml"
for v in $CILIUM_OLD $CILIUM_NEW; do
  for apiv in v2 v2alpha1; do
    names=$(curl -fsSL -m 60 "https://api.github.com/repos/cilium/cilium/contents/pkg/k8s/apis/cilium.io/client/crds/$apiv?ref=$v" \
      | "$PYTHON" -c 'import json,sys; print("\n".join(sorted(e["name"] for e in json.load(sys.stdin) if e["name"].endswith(".yaml"))))')
    for n in $names; do
      add "https://raw.githubusercontent.com/cilium/cilium/$v/pkg/k8s/apis/cilium.io/client/crds/$apiv/$n"
    done
  done
done
add "https://github.com/kubernetes-sigs/gateway-api/releases/download/$GATEWAY_API/experimental-install.yaml"
add "https://github.com/prometheus-operator/prometheus-operator/releases/download/$PROM_OPERATOR/stripped-down-crds.yaml"
for k in volumesnapshotclasses volumesnapshotcontents volumesnapshots; do
  add "https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/$SNAPSHOTTER/client/config/crd/snapshot.storage.k8s.io_$k.yaml"
done
add "https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/$BARMAN/manifest.yaml"

gen="$work/gen"
mkdir -p "$gen"
{
  echo "# Sources of the vendored CRD schemas, sha256sum format (generated by scripts/ci/gen-crd-schemas.sh)."
  echo "# The last line is the Kubernetes OpenAPI document the CustomResourceDefinition schema is built from."
  echo "$O2J_SHA256  $O2J_URL"
} > "$work/SOURCES.txt"

i=0
for url in "${sources[@]}"; do
  i=$((i + 1))
  f="$work/src-$i.yaml"
  curl -fsSL -m 120 -o "$f" "$url" || { echo "gen-crd-schemas: fetch failed: $url" >&2; exit 1; }
  echo "$(sha256 "$f")  $url" >> "$work/SOURCES.txt"
  (cd "$gen" && FILENAME_FORMAT='{fullgroup}_{kind}_{version}' "$PYTHON" "$work/openapi2jsonschema.py" "$f" >/dev/null)
done

curl -fsSL -m 120 -o "$work/k8s-apiextensions.json" "$K8S_OPENAPI" || { echo "gen-crd-schemas: fetch failed: $K8S_OPENAPI" >&2; exit 1; }
echo "$(sha256 "$work/k8s-apiextensions.json")  $K8S_OPENAPI" >> "$work/SOURCES.txt"
"$PYTHON" "$ROOT/scripts/ci/k8s_openapi_to_schema.py" "$work/k8s-apiextensions.json" "$CRD_DEF" \
  "$gen/apiextensions.k8s.io_customresourcedefinition_v1.json" --opaque "$CRD_OPAQUE"

rm -rf "$OUT"
mkdir -p "$OUT"
cp "$gen"/*.json "$OUT"/
cp "$work/SOURCES.txt" "$OUT/SOURCES.txt"
echo "gen-crd-schemas: $(find "$OUT" -name '*.json' | wc -l | tr -d ' ') schemas from ${#sources[@]} sources in ci/schemas/"
