---
# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json

clusterName: nedsi-homelab

# renovate: datasource=github-releases depName=siderolabs/talos
talosVersion: v1.7.5

# renovate: datasource=github-releases depName=siderolabs/kubelet
kubernetesVersion: v1.30.3

endpoint: https://192.168.1.11:6443

allowSchedulingOnControlPlanes: true

additionalApiServerCertSans: &san
  - 192.168.1.11
  - 127.0.0.1

additionalMachineCertSans: *san

cniConfig:
  name: none

nodes:
  - hostname: tm-0
    ipAddress: 192.168.1.247
    controlPlane: true
    installDisk: /dev/mmcblk0
    networkInterfaces:
      - interface: enx52dccfda3046
        dhcp: true
        vip:
          ip: 192.168.1.11
    nodeLabels:
      rack: turingpi

  - hostname: tm-1
    ipAddress: 192.168.1.238
    controlPlane: true
    installDisk: /dev/mmcblk0
    networkInterfaces:
      - interface: enx86d924a1276b
        dhcp: true
        vip:
          ip: 192.168.1.11
    nodeLabels:
      rack: turingpi

  - hostname: tm-2
    ipAddress: 192.168.1.239
    controlPlane: true
    installDisk: /dev/mmcblk0
    networkInterfaces:
      - interface: enx86d924a1276b
        dhcp: true
        vip:
          ip: 192.168.1.11
    nodeLabels:
      rack: turingpi

  - hostname: tw-0
    ipAddress: 192.168.1.240
    controlPlane: false
    installDisk: /dev/mmcblk0
    networkInterfaces:
      - interface: enx5eaa023eaa11
        dhcp: true
    nodeLabels:
      rack: turingpi

controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools

  patches:
    # Enable KubePrism
    - &kubePrismPatch |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445

    # TuringPi stuff
    - &turingPiPatch |-
      machine:
        kernel:
          modules:
            - name: rockchip-cpufreq

    # Disabled kube-proxy as Cilium doesn't need it
    - &kubeProxyPatch |-
      cluster:
        proxy:
          disabled: true

    # Enable K8s Talos API Access
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
              - os:admin
            allowedKubernetesNamespaces:
              - kube-system

    # Cluster configuration
    - |-
      cluster:
        allowSchedulingOnMasters: true

worker:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/iscsi-tools

  patches:
    - *kubePrismPatch
    - *turingPiPatch
    - *kubeProxyPatch
