---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: radarr
  name: radarr
  namespace: theater
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7878
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: radarr
