---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: 188.155.74.203
  labels:
    app.kubernetes.io/name: paperless
  name: paperless
  namespace: paperless
spec:
  ingressClassName: nginx
  rules:
  - host: archive.lilalala.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: paperless
            port:
              name: http
  tls:
  - hosts:
    - archive.lilalala.com
    secretName: paperless-tls
