---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: theater
spec:
  storageClassName: iscsi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode
  namespace: theater
spec:
  storageClassName: iscsi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
