apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

# Resources the Immich chart does not provide.
resources:
  - database.yaml
  - library-pvc.yaml
  - httproute.yaml
  - backup.yaml
  - backup-files.yaml
