apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-pvc
  namespace: mealie
spec:
  storageClassName: iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
