---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mealie
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  strategy:
    rollingUpdate: null
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mealie
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v2.4.0
          imagePullPolicy: Always
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: TZ
              value: Europe/Zurich
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: BASE_URL
              value: "https://cook.lilalala.com"
            - name: DB_ENGINE
              value: "postgres"
            - name: mealie__LOG__DBENABLED
              value: "false"
            - name: POSTGRES_SERVER
              valueFrom:
                secretKeyRef:
                  name: mealie-postgresql-app
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: mealie-postgresql-app
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-postgresql-app
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-postgresql-app
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mealie-postgresql-app
                  key: dbname
            - name: OIDC_AUTH_ENABLED
              value: "true"
            - name: OIDC_CONFIGURATION_URL
              value: "https://auth.lilalala.com/.well-known/openid-configuration"
            - name: OIDC_CLIENT_ID
              value: mealie
            - name: OIDC_CLIENT_SECRET
              value: biLeDqKXKye0huL4hICl53zLXfVXZ4ep
            - name: OIDC_AUTO_REDIRECT
              value: "true"
            - name: OIDC_PROVIDER_NAME
              value: "Keycloak"
            - name: OIDC_REMEMBER_ME
              value: "true"
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          resources:
            limits:
              memory: "1000Mi"
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-pvc
