apiVersion: v1
kind: ConfigMap
metadata:
  name: telly-config
  namespace: theater
data:
  telly.config.toml: |
    [Discovery]
      Device-Auth = "telly"
      Device-Friendly-Name = "telly"

    [IPTV]
      FFMpeg = true

    [Log]
      Level = "debug"
      Requests = true

    [Web]
      Listen-Address = "0.0.0.0:6077"

    [[Source]]
      Name = "TV7"
      Provider = "Custom"
      M3U = "https://api.init7.net/tvchannels.m3u?rp=true"
      EPG = "https://github.com/mathewmeconry/TV7_EPG_Data/raw/master/tv7_init7_epg.xml.gz"
