---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: prowlarr
  name: prowlarr
  namespace: theater
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9696
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: prowlarr
